### PR TITLE
Remove Gemfile.lock from index, implement after_action

### PR DESCRIPTION
**Pull request by redbassett**
Gemfile.lock should not be tracked in gems.

Implement `after_action` instead of `after_filter` in compliance with upcoming rails change removing `after_filter` in 5.1.

### CODE REVIEW

**Comment by redbassett** [comment]
Added change of `after_filter` to `after_action` to pull request.

**Comment by jsanders** [comment]
You're right, the `Gemfile.lock` definitely shouldn't be tracked!

However, we're purposefully using `_filter` instead of `_action` so that it works with Rails 3. This is why the tests are failing in this branch.

I went ahead and did *just* the `Gemfile.lock` change in #11.

**Comment by redbassett** [comment]
Sounds good! I was unaware, that Rails 3 didn't support `_action`, but that is a good reason to keep it! If there is a plan to branch off some sort of 5-compatible version in the future, that change should make it in :stuck_out_tongue: 

Thanks!

**Comment by jsanders** [comment]
Yeah I attempted to test against Rails master in #12 but ran into completely unrelated issues and decided it isn't baked enough yet to bother. But at some point, I'll release a new major version that drops support for 3 while adding support for 5.

**Pull request closed without merging**
