### PR TITLE
Update for rails 5

### PR DESCRIPTION
**Pull request by tpmullan**
I bumped the required version of rails so it will install.   It seems to work fine for me, but please look it over more.  All the tests passed on my system

### CODE REVIEW

**Comment by teoljungberg** [comment]
Since Rails 5 was released yesterday, it might be good to start looking into this again.

Is there anything I can do to help?

**Comment by heptaman** [comment]
Hi Guys, I am trying to upgrade to Rails 5 but this gem is stopping the process. I saw that this PR bumped the version required, but it was not accepted yet. What is the problem? Anything I can do to help with?

**Comment by tpmullan** [comment]
This has been working fine for me after my simple patch.  Not sure why the main repo hasn't been updated.

**Comment by heptaman** [comment]
Yeah, it works indeed, but I had to download the repo, build the gem and install locally. ;)

**Comment by tpmullan** [comment]
You can always use my repo and just reference github in your Gemfile. ( Examples at http://bundler.io/git.html )

**Comment by heptaman** [comment]
Cool! Thanks, man!

**Comment by jsanders** [comment]
Hey folks, my apologies! I haven't been using Angular for awhile (or checking my notifications, clearly). If someone is willing to take over maintenance of this gem (@tpmullan?), I would be happy to transfer ownership.

**Comment by tpmullan** [comment]
I am actually not really using angular any more, but if no one else wants to maintain this project I can at least update it for Rails 5

**Comment by bodrovis** [comment]
@jsanders  Hello! Me and my friend @kutanov are willing to maintain this project as we are using Angular and Rails pretty extensively

**Comment by jsanders** [comment]
Thanks @bodrovis! Sorry for the ridiculously slow response. Are you and @kutanov still willing to take this over? If so, I'll transfer it to you and add you as a gem owner. Is the email listed in your github profile the right one to use for rubygems?

**Comment by bodrovis** [comment]
@jsanders that's ok, no rush here. Yeah, we are using this in our projects. The e-mails are correct :)

**Comment by bodrovis** [comment]
@jsanders Thank you, I got your invitation. To be able to publish new gem versions I'll also require access to rubygems

**Comment by bodrovis** [comment]
Now in master, a new version of the gem will be released soon.

**Pull request closed without merging**
